version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  mongo-data:
